name: midone_scanner
description: MidONe Scanner SK - Shir Khorshid CDN IP Scanner
publish_to: 'none'
version: 7.2.0+6

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  path_provider: ^2.1.4
  google_fonts: ^6.2.1
  url_launcher: ^6.3.0
  shared_preferences: ^2.3.2
  flutter_local_notifications: ^17.2.4
  file_picker: ^8.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/app_icon.png
    - assets/icons/telegram_icon.png
    - assets/geo/ipcountry.bin
    - assets/xray/
