name: Build Android APK with Buildozer

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Cloud Code
      uses: actions/checkout@v4

    # قفل کردن پایتون روی نسخه پایدار 3.11 برای هماهنگی با کیوی
    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    # پاکسازی کش‌های خراب و قدیمی بیلدوزر برای جلوگیری از تداخل
    - name: Clear Buildozer Cache
      run: |
        rm -rf .buildozer/
        rm -rf ~/.buildozer/

    # نصب پیش‌نیازهای لینوکس (کلمه textidiom با موفقیت حذف شد)
    - name: Install System Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y git zip unzip openjdk-17-jdk autoconf libtool pkg-config zlib1g-dev libncurses5-dev libgdbm-dev libnss3-dev libssl-dev libreadline-dev libffi-dev libsqlite3-dev sqlite3 bzip2 libbz2-dev
        pip install --upgrade pip
        pip install buildozer kivy==2.3.0 cython

    # اجرای بیلدوزر با دستور yes برای تایید خودکار لایسنس‌ها در کنسول غیرتعاملی
    - name: Build Android App with Buildozer
      env:
        TERM: xterm
      run: |
        yes | buildozer android debug

    # آپلود فایل نهایی APK در بخش اکشنز گیت‌هاب
    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: MidONe-Scanner-APK
        path: bin/*.apk
